#
# A simple Makefile
#

######

all::

######

pullall:: \
bmroach
bmroach:: ; \
 cd cs320-2016-spring-bmroach && \
 git pull https://bithwxi:xav640707@bitbucket.org/bmroach/cs320-2016-spring-bmroach.git

######

pullall:: \
mchinni
mchinni:: ; \
 cd cs320-2016-spring-mchinni && \
 git pull https://bithwxi:xav640707@bitbucket.org/mchinni/cs320-2016-spring-mchinni.git

######

###### end of [Makefile] ######
