#
# A simple Makefile
#

######

all::

######

MYPASSWD=zoclo040512

######

pullall:: \
bken7
bken7:: ; \
 cd cs320-2016-spring-bken7 && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/BKen7/cs320-2016-spring-bken7.git

######

pullall:: \
bmroach
bmroach:: ; \
 cd cs320-2016-spring-bmroach && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/bmroach/cs320-2016-spring-bmroach.git

######

pullall:: \
cezzell
cezzell:: ; \
 cd cs320-2016-spring-cezzell && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/Cezzell/cs320-2016-spring-cezzell.git

######

pullall:: \
cjoe
cjoe:: ; \
 cd cs320-2016-spring-cjoe && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/cjoe95/cs320-2016-spring-cjoe.git

######

pullall:: \
hungweta
hungweta:: ; \
 cd cs320-2016-spring-hungweta && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/hungweta/cs320-2016-spring-hungweta.git

######

pullall:: \
jgrishey
jgrishey:: ; \
 cd cs320-2016-spring-u97564072 && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/jgrishey/cs320-2016-spring-u97564072.git

######

pullall:: \
jiayao
jiayao:: ; \
 cd cs320-2016-spring-jiayao && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/jiayao20757/cs320-2016-spring-jiayao.git

######

pullall:: \
jiazhang
jiazhang:: ; \
 cd cs320-2016-spring-jiazhang && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/jiahua_zhang/cs320-2016-spring-jiazhang.git

######

pullall:: \
mchinni
mchinni:: ; \
 cd cs320-2016-spring-mchinni && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/mchinni/cs320-2016-spring-mchinni.git

######

pullall:: \
rmwalshy
rmwalshy:: ; \
 cd cs320-2016-spring-rmwalshy && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/rmwalshy/cs320-2016-spring-rmwalshy.git

######

pullall:: \
robinliu
robinliu:: ; \
 cd cs320-2016-spring-robinliu && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/robinliu106/cs320-2016-spring-robinliu.git

######

pullall:: \
scarleth
scarleth:: ; \
 cd cs320-2016-spring-scarleth && \
 git pull https://bithwxi:$(MYPASSWD)@bitbucket.org/Scarleth/cs320-2016-spring-scarleth.git

######

###### end of [Makefile] ######
